data = """..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........
"""
data = data.split("\n")

possible_antenas = list("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
antenas_positions = []

# Find all the antenas
for line_index, line in enumerate(data):
  for char_index, char in enumerate(line):
    if char in possible_antenas:
      antenas_positions.append((char_index, line_index))

print(antenas_positions)
